# Generated by Django 3.1.3 on 2022-07-22 09:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=200)),
                ('date_and_time', models.DateTimeField()),
                ('organisers_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('followers', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('online_type', models.CharField(blank=True, max_length=200, null=True)),
                ('map_lat', models.CharField(blank=True, max_length=200, null=True)),
                ('map_long', models.CharField(max_length=200)),
                ('refund_policy', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('eventcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_pattern_list', to='event_name.eventcard')),
            ],
        ),
    ]
