# Generated by Django 3.1.3 on 2022-06-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=200)),
                ('date_and_time', models.DateTimeField()),
                ('organisers_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('followers', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('online_type', models.CharField(max_length=200)),
                ('map_lat', models.CharField(max_length=200)),
                ('map_long', models.CharField(max_length=200)),
                ('refund_policy', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
