# Generated by Django 3.1.3 on 2022-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcard',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
