# Generated by Django 3.1.3 on 2022-06-09 07:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('event_name', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='description',
            field=tinymce.models.HTMLField(max_length=10000),
        ),
    ]
