# Generated by Django 3.1.3 on 2022-07-25 10:08

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_name', '0002_eventcard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=0, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
