# Generated by Django 3.1.3 on 2022-07-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_name', '0004_auto_20220726_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
