# Generated by Django 3.1.3 on 2022-07-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_name', '0005_auto_20220726_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
