# Generated by Django 3.1.3 on 2022-07-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_name', '0006_auto_20220726_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
