# Generated by Django 3.1.3 on 2022-07-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_name', '0007_auto_20220727_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
