# Generated by Django 3.1.3 on 2022-07-27 05:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_name', '0008_auto_20220727_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
