# Generated by Django 3.1.3 on 2022-08-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_name', '0009_auto_20220727_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcard',
            name='cover_image',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
