# Generated by Django 3.1.3 on 2022-08-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_paypal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(max_length=25)),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('cvc', models.CharField(max_length=50)),
                ('cardholder_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('address_line1', models.CharField(max_length=50)),
                ('address_line2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
            ],
        ),
    ]
