# Generated by Django 3.1.3 on 2022-05-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imageheader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('help_title', models.CharField(max_length=200)),
                ('help_description', models.CharField(max_length=200)),
            ],
        ),
    ]
